#!/usr/bin/env php
<?php

/*
 * --------------------------------------------------------------------
 * CodeIgniter command-line tools
 * --------------------------------------------------------------------
 * The main entry point into the CLI system and allows you to run
 * commands and perform maintenance on your application.
 *
 * Because CodeIgniter can handle CLI requests as just another web request,
 * this script mainly acts as a passthru to the framework itself.
 */

define('SPARKED', true);

/*
 *---------------------------------------------------------------
 * BOOTSTRAP THE APPLICATION
 *---------------------------------------------------------------
 * This process sets up the path constants, loads and registers
 * our autoloader, along with Composer's, loads our constants,
 * and fires up an environment-specific bootstrapping.
 */

// Refuse to run when called from php-cgi
if (substr(php_sapi_name(), 0, 3) === 'cgi') {
    die("The CLI tool is not supported when running php-cgi. It needs php-cli to function!\n\n");
}

// Set the path to the front controller
define('FCPATH', __DIR__ . '/public' . DIRECTORY_SEPARATOR);

// Load the paths configuration file and set the system directory
require 'app/Config/Paths.php'; // Update this line if you move your application folder
$paths = new Config\Paths();

// Ensure the current directory is pointing to the front controller's directory
chdir(FCPATH);

// Require the bootstrap file and create the application
$app = require rtrim($paths->systemDirectory, '/ ') . '/bootstrap.php';

// Create a Console instance
$console = new \CodeIgniter\CLI\Console($app);

// Show errors when using the CLI
error_reporting(-1);
ini_set('display_errors', 1);

// Show basic information before processing any command
$console->showHeader();

// Execute the command in the main framework
$response = $console->run();
if ($response->getStatusCode() >= 300) {
    exit($response->getStatusCode());
}
